# DSN (Database Source Name) to connect databasef
dsn: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}?hide_auto_increment
# Path to generate document
# Default is `dbdoc`
docPath: docs/db

exclude:
  - _prisma_migrations
