services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 3001:3001
    env_file:
      - .env.dev
    tty: true
    init: true
    volumes:
      - .:/root/app
      - node_modules_volume:/root/app/node_modules
    networks:
      - defualt_network

  db:
    image: mysql:5.7
    hostname: mysql
    env_file:
      - .env.dev
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/log:/var/log/mysql
    ports:
      - 3301:3306
    networks:
      - defualt_network

networks:
  defualt_network:
    driver: bridge
volumes:
  node_modules_volume:
