version: '3'

dotenv: ['.env.$ENV']
tasks:
  serve:
    desc: サーバー起動
    cmds:
      - npx nest start -b swc -w
  serve:prod:
    desc: 本番サーバー検証
    cmds:
      - npx node dist/main
  build:
    desc: ビルド
    cmds:
      - npm run build
  resource:
    desc: リソースの自動生成
    cmds:
      - npm run resource -name={{ .CLI_ARGS }}
  mysql:
    desc: mysqlに接続
    cmds:
      - mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD
  db:refresh:
    desc: DBの初期化
    prompt: これを実行するとDBの情報が削除されます。本当によろしいですか?
    cmds:
      - echo "drop database $MYSQL_DATABASE;" | mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD
      - echo "create database $MYSQL_DATABASE;" | mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD
      - taks db:grant
  db:grant:
    desc: Prismaでmysqlを使用するとき用の権限設定
    cmds:
      - echo "GRANT CREATE, ALTER, DROP, REFERENCES ON *.* to 'admin'@'%';" | mysql -h $MYSQL_HOST -u root -p$MYSQL_PASSWORD $MYSQL_DATABASE
  db:seed:
    desc: シーダー
    cmds:
      - npx ts-node prisma/seed.ts
  migrate:
    desc: マイグレーションファイル自動生成と実行 task migrate:generate -- message
    cmds:
      - dotenv -e .env.dev -- npx prisma migrate dev --name {{ .CLI_ARGS }}
      - task er-update
  migrate:reset:
    desc: マイグレーションリセット
    cmds:
      - dotenv -e .env.dev -- npx prisma migrate reset
  migrate:studio:
    desc: マイグレーションGUI
    cmds:
      - npx prisma studio
  er-update:
    desc: ER図を更新
    cmds:
      - tbls doc -f
