version: '3'

dotenv: ['.env.$ENV']
tasks:
  install:
    desc: パッケージのインストール
    cmds:
      - npm install
  setup:
    desc: セットアップ
    cmds:
      - npm install
      - npx drizzle-kit migrate
  lint:
    desc: リント
    cmds:
      - npx biome lint ./src
  lint-fix:
    desc: リント修正
    cmds:
      - npx biome check --write ./src
  serve:
    desc: サーバー起動
    cmds:
      - npx nest start -w
  build:
    desc: ビルド
    cmds:
      - npx nest build
  resource:
    desc: リソースの自動生成
    cmds:
      - npx nest g resource {{ .CLI_ARGS }}
  mysql:
    desc: mysqlに接続
    cmds:
      - mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD
  db:refresh:
    desc: DBの初期化
    prompt: これを実行するとDBの情報が削除されます。本当によろしいですか?
    cmds:
      - echo "drop database $MYSQL_DATABASE;" | mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD
      - echo "create database $MYSQL_DATABASE;" | mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD
  db:seed:
    desc: シーダー
    cmds:
      - npx tsx src/db/seeds/database.ts
  db:migrate:
    desc: マイグレーション実行
    cmds:
      - npx drizzle-kit migrate
  db:migrate:gen:
    desc: マイグレーションファイル自動生成
    cmds:
      - npx drizzle-kit generate --name {{ .CLI_ARGS }}
  db:studio:
    desc: DBGUI
    cmds:
      - npx drizzle-kit studio
  er-update:
    desc: ER図を更新
    cmds:
      - tbls doc -f
