name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value:
  - type: textarea
    id: what-happened
    attributes:
      label: 概要
      description:
      placeholder: Tell us what you see!
      value: "バグの概要を書いて下さい"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: エラーログ
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
